name: Recipe Changer
version: 0.6
author: lst96
main: io.github.lst96.RecipeChanger.Recipe
commands:
   recipereload:
       description: Reloads Configuration.
permissions:
    recipe.*:
        description: gives all permissions.
        children:
            recipe.reload: true
            recipe.ironhorse: true
            recipe.goldhorse: true
            recipe.diamondhorse: true
            recipe.nametag: true
            recipe.gunpowder: true
            recipe.dragonegg: true
            recipe.redstoneore: true
            recipe.saddle: true
            recipe.bedrock: true 
            recipe.sponge: true
            recipe.enchanting: true
            recipe.chainleggings: true
            recipe.chainboots: true
            recipe.chainhelmet: true
            recipe.chainchest: true 
            recipe.fire: true
            recipe.chiseled: true
            recipe.tallgrass: true 
            recipe.grassblock: true
            recipe.ice: true
            recipe.mossbrick: true
            recipe.mossstone: true
            recipe.cobweb: true
            recipe.mobspawner: true
            recipe.command: true
            recipe.podzol: true
            recipe.doubletallgrass: true
    recipe.member:
        description: gives all permissions except reload.
        children:
            recipe.reload: false
            recipe.ironhorse: true
            recipe.goldhorse: true
            recipe.diamondhorse: true
            recipe.nametag: true
            recipe.gunpowder: true
            recipe.dragonegg: true
            recipe.redstoneore: true
            recipe.saddle: true
            recipe.bedrock: true 
            recipe.sponge: true
            recipe.enchanting: true
            recipe.chainleggings: true
            recipe.chainboots: true
            recipe.chainhelmet: true
            recipe.chainchest: true 
            recipe.fire: true
            recipe.chiseled: true
            recipe.tallgrass: true 
            recipe.grassblock: true
            recipe.ice: true
            recipe.mossbrick: true
            recipe.mossstone: true
            recipe.cobweb: true
            recipe.mobspawner: true
            recipe.command: true
            recipe.podzol: true
            recipe.doubletallgrass: true
    recipe.reload:
        description: Allows use of recipereload command.
    recipe.ironhorse:
        description: Allows ability to craft iron horse armor.
    recipe.goldhorse:
        description: Allows ability to craft gold horse armor.
    recipe.diamondhorse:
        description: Allows ability to craft diamond horse armor.
    recipe.nametag:
        description: Allows ability to craft a nametag.
    recipe.gunpowder:
        description: Allows ability to craft gunpowder.
    recipe.dragonegg:
        description: Allows ability to craft dragoneggs.
    recipe.redstoneore:
        description: Allows ability to craft redstone ore.
    recipe.saddle:
        description: Allows ability to craft saddles.
    recipe.bedrock:
        description: Allows ability to craft bedrock.
    recipe.sponge:
        description: Allows ability to craft sponges.
    recipe.enchanting:
        description: Allows ability to craft Exp Bottles.
    recipe.chainleggings:
        description: Allows ability to craft chain leggings.
    recipe.chainboots:
        description: Allows ability to craft chain boots.
    recipe.chainhelmet:
        description: Allows ability to craft chain helmets.
    recipe.chainchest:
        description: Allows ability to craft chain chestpiece.
    recipe.fire:
        description: Allows ability to craft fire.
    recipe.chiseled:
        description: Allows ability to craft Chiseled Brick.
    recipe.tallgrass:
        description: Allows ability to craft Tall grass.
    recipe.grassblock:
        description: Allows ability to craft Grass blocks.
    recipe.ice:
        description: Allows ability to craft ice blocks.
    recipe.mossbrick:
        description: Allows ability to craft Moss Bricks.
    recipe.mossstone:
        descriptoin: Allows ability to craft Moss Stone.
    recipe.cobweb:
        description: Allows ability to craft cobwebs.
    recipe.mobspawner:
        description: Allows ability to craft Mob Spawners.
    recipe.command:
        description: Allows ability to craft Command Blocks.
    recipe.podzol:
        description: Allows ability to craft Podzol.
    recipe.doubletallgrass:
        description: Allows ability to craft Double TallGrass.
  