name: Recipe Changer
version: 0.8
author: lst96
main: io.github.lst96.RecipeChanger.Recipe
commands:
   recipereload:
       description: Reloads Configuration.
permissions:
    recipe.*:
        description: gives all permissions.
        children:
            recipe.reload: true
            recipe.ironhorse: true
            recipe.goldhorse: true
            recipe.diamondhorse: true
            recipe.nametag: true
            recipe.gunpowder: true
            recipe.dragonegg: true
            recipe.redstoneore: true
            recipe.saddle: true
            recipe.bedrock: true 
            recipe.sponge: true
            recipe.enchanting: true
            recipe.chainleggings: true
            recipe.chainboots: true
            recipe.chainhelmet: true
            recipe.chainchest: true 
            recipe.fire: true
            recipe.chiseled: true
            recipe.tallgrass: true 
            recipe.grassblock: true
            recipe.ice: true
            recipe.mossbrick: true
            recipe.mossstone: true
            recipe.cobweb: true
            recipe.mobspawner: true
            recipe.command: true
            recipe.podzol: true
            recipe.doubletallgrass: true
            recipe.packedice: true
            recipe.cowegg: true
            recipe.chickenegg: true
            recipe.sheepegg: true
            recipe.horseegg: true
            recipe.bategg: true
            recipe.mooshroomegg: true
            recipe.ocelotegg: true
            recipe.squidegg: true
            recipe.wolfegg: true
            recipe.pigegg: true
            recipe.obsidian: true
    recipe.member:
        description: gives all permissions except reload.
        children:
            recipe.reload: false
            recipe.ironhorse: true
            recipe.goldhorse: true
            recipe.diamondhorse: true
            recipe.nametag: true
            recipe.gunpowder: true
            recipe.dragonegg: false
            recipe.redstoneore: true
            recipe.saddle: true
            recipe.bedrock: false
            recipe.sponge: true
            recipe.enchanting: true
            recipe.chainleggings: true
            recipe.chainboots: true
            recipe.chainhelmet: true
            recipe.chainchest: true 
            recipe.fire: false
            recipe.chiseled: true
            recipe.tallgrass: true 
            recipe.grassblock: true
            recipe.ice: true
            recipe.mossbrick: true
            recipe.mossstone: true
            recipe.cobweb: true
            recipe.mobspawner: false
            recipe.command: false
            recipe.podzol: true
            recipe.doubletallgrass: true
            recipe.packedice: true
            recipe.cowegg: true
            recipe.chickenegg: true
            recipe.sheepegg: true
            recipe.horseegg: true
            recipe.bategg: true
            recipe.mooshroomegg: true
            recipe.ocelotegg: true
            recipe.squidegg: true
            recipe.wolfegg: true
            recipe.pigegg: true
            recipe.obsidian: true
    recipe.admin:
        description: gives all permissions except reload.
        children:
            recipe.reload: false
            recipe.ironhorse: true
            recipe.goldhorse: true
            recipe.diamondhorse: true
            recipe.nametag: true
            recipe.gunpowder: true
            recipe.dragonegg: true
            recipe.redstoneore: true
            recipe.saddle: true
            recipe.bedrock: true 
            recipe.sponge: true
            recipe.enchanting: true
            recipe.chainleggings: true
            recipe.chainboots: true
            recipe.chainhelmet: true
            recipe.chainchest: true 
            recipe.fire: true
            recipe.chiseled: true
            recipe.tallgrass: true 
            recipe.grassblock: true
            recipe.ice: true
            recipe.mossbrick: true
            recipe.mossstone: true
            recipe.cobweb: true
            recipe.mobspawner: true
            recipe.command: true
            recipe.podzol: true
            recipe.doubletallgrass: true
            recipe.packedice: true
            recipe.cowegg: true
            recipe.chickenegg: true
            recipe.sheepegg: true
            recipe.horseegg: true
            recipe.bategg: true
            recipe.mooshroomegg: true
            recipe.ocelotegg: true
            recipe.squidegg: true
            recipe.wolfegg: true
            recipe.pigegg: true
            recipe.obsidian: true