name: Recipe Changer
version: 0.6
author: lst96
main: io.github.lst96.RecipeChanger.Recipe
commands:
   recipereload:
       description: Reloads Configuration.
permissions:
    recipe.*:
        description: gives all permissions.
        children:
            recipe.reload: true
            recipe.ironhorse: true
            recipe.goldhorse: true
            recipe.diamondhorse: true
            recipe.nametag: true
            recipe.gunpowder: true
            recipe.dragonegg: true
            recipe.redstoneore: true
            recipe.saddle: true
            recipe.bedrock: true 
            recipe.sponge: true
            recipe.enchanting: true
            recipe.chainleggings: true
            recipe.chainboots: true
            recipe.chainhelmet: true
            recipe.chainchest: true 
            recipe.fire: true
            recipe.chiseled: true
            recipe.tallgrass: true 
            recipe.grassblock: true
            recipe.ice: true
            recipe.mossbrick: true
            recipe.mossstone: true
            recipe.cobweb: true
            recipe.mobspawner: true
            recipe.command: true
            recipe.podzol: true
            recipe.doubletallgrass: true
    recipe.member:
        description: gives all permissions except reload.
        children:
            recipe.reload: false
            recipe.ironhorse: true
            recipe.goldhorse: true
            recipe.diamondhorse: true
            recipe.nametag: true
            recipe.gunpowder: true
            recipe.dragonegg: true
            recipe.redstoneore: true
            recipe.saddle: true
            recipe.bedrock: true 
            recipe.sponge: true
            recipe.enchanting: true
            recipe.chainleggings: true
            recipe.chainboots: true
            recipe.chainhelmet: true
            recipe.chainchest: true 
            recipe.fire: true
            recipe.chiseled: true
            recipe.tallgrass: true 
            recipe.grassblock: true
            recipe.ice: true
            recipe.mossbrick: true
            recipe.mossstone: true
            recipe.cobweb: true
            recipe.mobspawner: true
            recipe.command: true
            recipe.podzol: true
            recipe.doubletallgrass: true
  